### PR TITLE
Move ESAPI repo to an SFDX project format

### PR DESCRIPTION
**Pull request by capeterson**

### CODE REVIEW

**Comment by capeterson** [comment]
@voppon - any objections? No code changes, just repo layout modernization.

Will merge end of day Friday if none are raised by you or others.

**Comment by FishOfPrey** [comment]
Should the .vscode directory be included in the repo?
.vscode/settings.json has a path specific to you.

**Comment by voppon** [comment]
@capeterson I don't think you want your .vscode/settings.json to be there do you?

**Comment by capeterson** [comment]
.vscode should be in general, since it has things like suggested plugins that make running easier with the official SFDX toolchain. But you're right, settings.json should be excluded. Fixing.

**Pull request merged**
